server:
  port: 8002

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8002

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://39.105.33.148:3306/haiyang_db2020?useUnicode=true&characterEncoding-utr-8&useSSL=false
    username: root
    password: Abc123!
    druid:
      test-while-idle: true
      initial-size: 2
      max-active: 300
      filter: stat
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-on-borrow: false
      test-on-return: false
      max-pool-prepared-statement-per-connection-size: 200
      pool-prepared-statements: false

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.ocean.springcloud.entities      #所有Entity别名类所在包
    configuration:
      map-underscore-to-camel-case: true